modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0+"
issueTrackerURL="https://github.com/ItzSwirlz/obsidian-diamond-ores-mod/issues"

[[mods]]
modId="obsidiandiamondoresmod"
version="${file.jarVersion}"
displayName="Obsidian Diamond Ores Mod"
updateJSONURL="https://github.com/ItzSwirlz/obsidian-diamond-ores-mod/blob/main/update.json"
displayURL="https://github.com/ItzSwirlz/obsidian-diamond-ores-mod"	# FIXME: Possibly on curseforge?
#logoFile="examplemod.png" # TODO: Icon
credits="Thanks to MCChewy for his first ever 1.7x tutorials on making a mod that got me started in the first place."
authors="Joshua Peisach (ItzSwirlz)"
description='''
The Obsidian Diamond Ores Mod!

Adds tools and armor of a mix of Obsidian and Diamond armor.
'''